#!/usr/bin/env bash
set -euo pipefail

# ========== Settings ==========
# Workspace root (adjust to your Dev Container runtime path)
# For VS Code Dev Containers
WORKSPACE_ROOT="${WORKSPACE_ROOT:-/workspaces}"

SENSOR_REPO_URL="https://github.com/SonySemiconductorSolutions/aitrios-edge-device-core-sensor.git"
SENSCORD_DEV_URL="https://github.com/SonySemiconductorSolutions/senscord-dev.git"
WRAP_FILE_PATH="subprojects/senscord.wrap"

# Use mktemp to avoid conflicts with parallel executions
TEMP_SENSOR_DIR="${TEMP_SENSOR_DIR:-$(mktemp -d -t sensor-repo.XXXXXX)}"
trap 'rm -rf "$TEMP_SENSOR_DIR"' EXIT
SENSCORD_DEV_DIR="${SENSCORD_DEV_DIR:-${WORKSPACE_ROOT}/test/include/senscord_dev}"

# ========== GitHub App Token Authentication (CI/CD) ==========
# Configure git credential helper when GIT_AUTH_TOKEN is provided
# Token is generated by GitHub App in CI workflow
if [[ -n "${GIT_AUTH_TOKEN:-}" ]]; then
  echo "[info] Configuring git authentication with provided token"

  # Use environment variables instead of config files to avoid permission issues
  export GIT_TERMINAL_PROMPT=0

  # Configure credential helper via environment
  CRED_FILE="${HOME:-/tmp}/.git-credentials"
  mkdir -p "$(dirname "${CRED_FILE}")"

  # Configure credentials for GitHub repositories
  for repo_url in "${SENSOR_REPO_URL}" "${SENSCORD_DEV_URL}"; do
    host=$(echo "${repo_url}" | sed -E 's|https?://([^/]+).*|\1|')
    echo "https://oauth2:${GIT_AUTH_TOKEN}@${host}" >> "${CRED_FILE}"
  done

  chmod 600 "${CRED_FILE}"
  export GIT_CONFIG_COUNT=1
  export GIT_CONFIG_KEY_0="credential.helper"
  export GIT_CONFIG_VALUE_0="store --file=${CRED_FILE}"

  echo "[info] Git credentials configured successfully"
else
  echo "[info] Using host git configuration (local development)"
fi

# ========== Sanity checks ==========
if [[ "${WORKSPACE_ROOT}" == "/" || -z "${WORKSPACE_ROOT}" ]]; then
  echo "[error] Invalid WORKSPACE_ROOT: '${WORKSPACE_ROOT}'"
  exit 1
fi

mkdir -p "${WORKSPACE_ROOT}"
cd "${WORKSPACE_ROOT}"

# ========== Process ==========
echo "[info] Cloning sensor repo (shallow): ${SENSOR_REPO_URL} -> ${TEMP_SENSOR_DIR}"
rm -rf "${TEMP_SENSOR_DIR}"
git clone --depth 1 "${SENSOR_REPO_URL}" "${TEMP_SENSOR_DIR}"

WRAP_FILE="${TEMP_SENSOR_DIR}/${WRAP_FILE_PATH}"
if [[ ! -f "${WRAP_FILE}" ]]; then
  echo "[error] Required wrap file not found in cloned repository: ${WRAP_FILE_PATH}"
  echo "[error] Please check if the repository structure has changed."
  exit 1
fi

REVISION=$(grep -E '^revision[[:space:]]*=' "${WRAP_FILE}" | head -n1 | sed -E 's/^revision[[:space:]]*=[[:space:]]*//')
if [[ $(grep -c -E '^revision[[:space:]]*=' "${WRAP_FILE}") -gt 1 ]]; then
  echo "[warn] Multiple 'revision' entries found in wrap file, using first one"
fi
if [[ -z "${REVISION}" ]]; then
  echo "[error] Failed to extract 'revision' from ${WRAP_FILE}"
  exit 1
fi
echo "[info] Found senscord-dev revision: ${REVISION}"

# ========== Remove destination directory before cloning ==========
if [[ -z "${SENSCORD_DEV_DIR}" || "${SENSCORD_DEV_DIR}" == "/" ]]; then
  echo "[error] Invalid SENSCORD_DEV_DIR: '${SENSCORD_DEV_DIR}'"
  exit 1
fi

# Normalize path and verify it's within workspace
SENSCORD_DEV_DIR=$(realpath -m "${SENSCORD_DEV_DIR}")
if [[ ! "${SENSCORD_DEV_DIR}" =~ ^"${WORKSPACE_ROOT}" ]]; then
  echo "[error] SENSCORD_DEV_DIR must be within WORKSPACE_ROOT"
  echo "[error] SENSCORD_DEV_DIR: ${SENSCORD_DEV_DIR}"
  echo "[error] WORKSPACE_ROOT: ${WORKSPACE_ROOT}"
  exit 1
fi

if [[ -d "${SENSCORD_DEV_DIR}" ]]; then
  echo "[info] Removing existing directory: ${SENSCORD_DEV_DIR}"
  rm -rf "${SENSCORD_DEV_DIR}"
fi

echo "[info] Cloning senscord-dev: ${SENSCORD_DEV_URL} -> ${SENSCORD_DEV_DIR}"
git clone "${SENSCORD_DEV_URL}" "${SENSCORD_DEV_DIR}"

cd "${SENSCORD_DEV_DIR}"
echo "[info] Checking out ${REVISION}"
git checkout "${REVISION}"

REV_SHORT=$(git rev-parse --short HEAD || echo "unknown")
COMMIT_DATE=$(git log -1 --format=%cd --date=short || echo "unknown")

cat > VERSION <<EOF
# SensCord-dev version information
# Auto-cloned during post-create from aitrios-edge-device-core-sensor revision

Repository: ${SENSCORD_DEV_URL}
Commit: ${REV_SHORT}
Revision: ${REVISION}
Date: ${COMMIT_DATE}
License: Apache-2.0
EOF

echo "[info] Done. senscord-dev cloned successfully at revision ${REVISION}"
echo "[info] Temporary files will be cleaned up automatically"